### ISSUE TITLE
No audio, no notifications. Are they suppose to be working?

### ISSUE THREAD

**Issue by skazzyskills** [birkir/homebridge-plugin-eufy-security#33]
**Describe The Bug:**
I get no notifications on my phone, or HomePod, when someone rings, or motion is detected. Am I suppose to?

**Comment by skazzyskills** [comment]
@birkir just wondering if this is possible?

**Comment by birkir** [comment]
They dont work yet, two way audio would be possible once we know how to do it via the API

**Comment by Josje92** [comment]
Regarding to the TODO here, notifications don't work yet.

[https://github.com/birkir/homebridge-plugin-eufy-security/blob/master/src/platform.ts:142](https://github.com/birkir/homebridge-plugin-eufy-security/blob/master/src/platform.ts)

**Comment by ElvisPresly** [comment]
I also don't have doorbell notifications and notifications if there is movement before the bell. Will this be fixed? Where can I make a donation?

**Comment by Josje92** [comment]
I'm planning on reverse engineering [the ring homebridge plugin](https://github.com/dgreif/ring/tree/master/homebridge#homebridge-ring) combined with what I can find here.

They even got sip-communication working through Homebridge, including Apple TV notifications and everything.

I think the biggest bottleneck is going to be reverse engineering those parts of the api, since not everything was reverse engineered for Eufy at this time of writing. Eufy support has proven very helpful for me though, so maybe they can be of assistance...

If you're a hacker and have one of these doorbells laying around, feel free to help out discovering every api endpoint there is.

**Comment by skazzyskills** [comment]
My friend if you do get this working please make sure you have a donate button so we can support the hard work. It would be great if this does get fixed

Shawn Skalinski
sskalinski@icloud.com

**Comment by Josje92** [comment]
This message alone increases my motivation 😉!

Will keep you guys posted, but as I said, I can't promise anything. If I have no way of getting to know the missing API-endpoints, the quest ends there.

**Comment by SSpecken** [comment]
There are several active projects already which are trying to connect to eufy-security:

https://github.com/JanLoebel/eufy-node-client
https://github.com/bropat/ioBroker.eufy-security

And a donate button is a really good idea!

**Comment by Josje92** [comment]
Thanks @SSpecken I saw some useful info there!

Setup my repo and will get hacking!
[https://github.com/Josje92/homebridge-eufy-doorbell](https://github.com/Josje92/homebridge-eufy-doorbell)

![Alt Text](https://s3.us-east-2.amazonaws.com/uptrend/posts/1601447200-35944.gif)

Wish me luck!

**Comment by SSpecken** [comment]
Good luck! I hope that the first cup of coffee for you is mine ;-)

**Comment by Josje92** [comment]
Hey thanks man! It is! As soon as our current lockdown ends, I'll be grabbing one 😊!

Cheers!

**Comment by skazzyskills** [comment]
Go on my son! For Asgaard!


Shawn Skalinski
sskalinski@icloud.com
